It's a trap!

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -241,43 +241,6 @@ jobs:
             mono-runtime libmono-system-json-microsoft4.0-cil libmono-system-data4.0-cil \
             libx11-dev libxcursor-dev libxrandr-dev libgl-dev libudev-dev libfreetype6-dev
 
-       #TODO: DEBUG START
-
-      - uses: aws-actions/configure-aws-credentials@v2
-        if: ${{ matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
-
-      - name: Download regression simulator binaries .zip from S3 bucket
-        if: ${{ matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
-        run: aws s3 cp "s3://${{ env.s3_bucket }}/regression_test/regression simulator ${{ env.regression_tests_target_tag }} (${{ matrix.name }}).zip" .
-
-      - name: Unzip regression simulator binaries
-        if: ${{ matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
-        run: unzip "regression simulator ${{ env.regression_tests_target_tag }} (${{ matrix.name }}).zip" -d ${{ env.regression_simulator_folder }}
-
-      - name: Add execute permissions to regression simulator
-        if: ${{ matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
-        run: chmod +x ${{ env.regression_simulator_folder }}/regression_simulator
-
-      - name: Run simulator and wait for it to to be ready
-        if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
-        run: |
-          ./${{ env.regression_simulator_folder }}/regression_simulator &
-          while [ ! -f ready ]; do sleep 1; done
-          echo "pid=$(pgrep -f regression_simulator)" >> $GITHUB_ENV
-
-      - name: Kill simulator gracefully and wait for exit
-        if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
-        run: |
-          echo pid is $pid
-          rm ready
-          while ps $pid > /dev/null; do sleep 1; done
-
-      # TODO: DEBUG END
-
       - name: Install latest CMake
         run: pip install cmake
 
@@ -317,7 +280,7 @@ jobs:
           path: ${{ env.package_path }}
           retention-days: 7
 
-      # REGRESSION TESTS BEGIN
+      # PROTOCOL REGRESSION TEST BEGIN
 
       - uses: aws-actions/configure-aws-credentials@v2
         if: ${{ matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
@@ -338,101 +301,85 @@ jobs:
         if: ${{ matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
         run: chmod +x ${{ env.regression_simulator_folder }}/regression_simulator
 
-      - name: Run simulator and wait for it to to be ready
-        if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
-        run: |
-          ./${{ env.regression_simulator_folder }}/regression_simulator &
-          while [ ! -f ready ]; do sleep 1; done
-
       - name: Protocol regression test - OPC UA
         if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
         env:
           GTEST_OUTPUT: "xml:${{ env.GITHUB_WORKSPACE }}/junit_reports/regression/opcua/"
-        run: cmake -E env protocol=opcua ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
-
-      - name: Kill simulator gracefully and wait for exit
-        if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
+          protocol: opcua
         run: |
-          pid=$(pgrep -f regression_simulator)
-          rm ready
-          while ps $pid > /dev/null; do sleep 1; done
-
-      - name: Run simulator and wait for it to to be ready
-        if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
-        run: |
+          # Run simulator and wait for it to to be ready
           ./${{ env.regression_simulator_folder }}/regression_simulator &
           while [ ! -f ready ]; do sleep 1; done
+          
+          # Set trap that will catch failed test (8) and successful test (0) and kill simulator gracefully, then exit with trapped code
+          trap "rc=$?; echo Killing simulator; pid=$(pgrep -f regression_simulator); rm ready; while ps $pid > /dev/null; do sleep 1; done; echo Simulator killed successfully; exit $rc" 0 8
+          
+          # Perform tests
+          ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
 
-      # TODO: debug only, DELETE THIS
       - name: Protocol regression test - FAIL
         if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
         env:
           GTEST_OUTPUT: "xml:${{ env.GITHUB_WORKSPACE }}/junit_reports/regression/fail/"
-        run: cmake -E env protocol=fail ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
-
-      - name: Kill simulator gracefully and wait for exit
-        if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
+          protocol: fail
         run: |
-          pid=$(pgrep -f regression_simulator)
-          rm ready
-          while ps $pid > /dev/null; do sleep 1; done
-
-      - name: Run simulator and wait for it to to be ready
-        if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
-        run: |
+          # Run simulator and wait for it to to be ready
           ./${{ env.regression_simulator_folder }}/regression_simulator &
           while [ ! -f ready ]; do sleep 1; done
+          
+          # Set trap that will catch failed test (8) and successful test (0) and kill simulator gracefully, then exit with trapped code
+          trap "rc=$?; echo Killing simulator; pid=$(pgrep -f regression_simulator); rm ready; while ps $pid > /dev/null; do sleep 1; done; echo Simulator killed successfully; exit $rc" 0 8
+          
+          # Perform tests
+          ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
 
       - name: Protocol regression test - ND
         if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
         env:
           GTEST_OUTPUT: "xml:${{ env.GITHUB_WORKSPACE }}/junit_reports/regression/nd/"
-        run: cmake -E env protocol=nd ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
-
-      - name: Kill simulator gracefully and wait for exit
-        if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
+          protocol: nd
         run: |
-          pid=$(pgrep -f regression_simulator)
-          rm ready
-          while ps $pid > /dev/null; do sleep 1; done
-
-      - name: Run simulator and wait for it to to be ready
-        if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
-        run: |
+          # Run simulator and wait for it to to be ready
           ./${{ env.regression_simulator_folder }}/regression_simulator &
           while [ ! -f ready ]; do sleep 1; done
+          
+          # Set trap that will catch failed test (8) and successful test (0) and kill simulator gracefully, then exit with trapped code
+          trap "rc=$?; echo Killing simulator; pid=$(pgrep -f regression_simulator); rm ready; while ps $pid > /dev/null; do sleep 1; done; echo Simulator killed successfully; exit $rc" 0 8
+          
+          # Perform tests
+          ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
 
       - name: Protocol regression test - NS
         if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
         env:
           GTEST_OUTPUT: "xml:${{ env.GITHUB_WORKSPACE }}/junit_reports/regression/ns/"
-        run: cmake -E env protocol=ns ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
-
-      - name: Kill simulator gracefully and wait for exit
-        if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
+          protocol: ns
         run: |
-          pid=$(pgrep -f regression_simulator)
-          rm ready
-          while ps $pid > /dev/null; do sleep 1; done
-
-      - name: Run simulator and wait for it to to be ready
-        if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
-        run: |
+          # Run simulator and wait for it to to be ready
           ./${{ env.regression_simulator_folder }}/regression_simulator &
           while [ ! -f ready ]; do sleep 1; done
+          
+          # Set trap that will catch failed test (8) and successful test (0) and kill simulator gracefully, then exit with trapped code
+          trap "rc=$?; echo Killing simulator; pid=$(pgrep -f regression_simulator); rm ready; while ps $pid > /dev/null; do sleep 1; done; echo Simulator killed successfully; exit $rc" 0 8
+          
+          # Perform tests
+          ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
 
       - name: Protocol regression test - LT
         if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
         env:
           GTEST_OUTPUT: "xml:${{ env.GITHUB_WORKSPACE }}/junit_reports/regression/lt/"
-        run: cmake -E env protocol=lt ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
-
-      - name: Kill simulator gracefully and wait for exit
-        if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
+          protocol: lt
         run: |
-          pid=$(pgrep -f regression_simulator)
-          rm ready
-          while ps $pid > /dev/null; do sleep 1; done
+          # Run simulator and wait for it to to be ready
+          ./${{ env.regression_simulator_folder }}/regression_simulator &
+          while [ ! -f ready ]; do sleep 1; done
+          
+          # Set trap that will catch failed test (8) and successful test (0) and kill simulator gracefully, then exit with trapped code
+          trap "rc=$?; echo Killing simulator; pid=$(pgrep -f regression_simulator); rm ready; while ps $pid > /dev/null; do sleep 1; done; echo Simulator killed successfully; exit $rc" 0 8
+          
+          # Perform tests
+          ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
 
       - name: Upload regression test results
         if: ${{ always() && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
@@ -441,7 +388,7 @@ jobs:
           name: Regression Test Results (${{ matrix.name }})
           path: ${{ env.GITHUB_WORKSPACE }}/junit_reports/regression
 
-      # REGRESSION TESTS END
+      # PROTOCOL REGRESSION TEST END
 
   build_linux_centos:
     runs-on: ubuntu-latest
