Introduce `regression_test_run.sh` (regression test runner script) in `ci.yml` so we don't have duplicated code in the file (the script is called for each protocol individually)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -301,86 +301,63 @@ jobs:
         if: ${{ matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
         run: chmod +x ${{ env.regression_simulator_folder }}/regression_simulator
 
+      - name: Create, save and give execute permissions to regression test runner script
+        if: ${{ matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
+        run: |
+          cat > regression_test_run.sh << EOL
+          
+          # Run simulator and wait for it to to be ready
+          ./${{ env.regression_simulator_folder }}/regression_simulator &
+          while [ ! -f ready ]; do sleep 1; done
+          
+          # Set trap that will catch failed (8) and successful (0) test and kill simulator gracefully, then exit with trapped code
+          trap "rc=\$?; echo Killing simulator; pid=\$(pgrep -f regression_simulator); rm ready; wait \$pid; echo Simulator killed successfully; exit \$rc" 0 8
+          
+          # Perform tests
+          ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
+          
+          EOL
+          
+          chmod +x regression_test_run.sh
+          
+          # TODO: DELETE THIS
+          cat regression_test_run.sh
+
       - name: Protocol regression test - OPC UA
         if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
         env:
           GTEST_OUTPUT: "xml:${{ env.GITHUB_WORKSPACE }}/junit_reports/regression/opcua/"
           protocol: opcua
-        run: |
-          # Run simulator and wait for it to to be ready
-          ./${{ env.regression_simulator_folder }}/regression_simulator &
-          while [ ! -f ready ]; do sleep 1; done
-          
-          # Set trap that will catch failed test (8) and successful test (0) and kill simulator gracefully, then exit with trapped code
-          trap "rc=$?; echo Killing simulator; pid=$(pgrep -f regression_simulator); rm ready; wait $pid; echo Simulator killed successfully; exit $rc" 0 8
-          
-          # Perform tests
-          ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
+        run: ./regression_test_run.sh
 
-      # DELETE THIS
+      # TODO: DELETE THIS
       - name: Protocol regression test - FAIL
         if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
         env:
           GTEST_OUTPUT: "xml:${{ env.GITHUB_WORKSPACE }}/junit_reports/regression/fail/"
           protocol: fail
-        run: |
-          # Run simulator and wait for it to to be ready
-          ./${{ env.regression_simulator_folder }}/regression_simulator &
-          while [ ! -f ready ]; do sleep 1; done
-          
-          # Set trap that will catch failed test (8) and successful test (0) and kill simulator gracefully, then exit with trapped code
-          trap "rc=$?; echo Killing simulator; pid=$(pgrep -f regression_simulator); rm ready; wait $pid; echo Simulator killed successfully; exit $rc" 0 8
-          
-          # Perform tests
-          ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
+        run: ./regression_test_run.sh
 
       - name: Protocol regression test - ND
         if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
         env:
           GTEST_OUTPUT: "xml:${{ env.GITHUB_WORKSPACE }}/junit_reports/regression/nd/"
           protocol: nd
-        run: |
-          # Run simulator and wait for it to to be ready
-          ./${{ env.regression_simulator_folder }}/regression_simulator &
-          while [ ! -f ready ]; do sleep 1; done
-          
-          # Set trap that will catch failed test (8) and successful test (0) and kill simulator gracefully, then exit with trapped code
-          trap "rc=$?; echo Killing simulator; pid=$(pgrep -f regression_simulator); rm ready; wait $pid; echo Simulator killed successfully; exit $rc" 0 8
-          
-          # Perform tests
-          ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
+        run: ./regression_test_run.sh
 
       - name: Protocol regression test - NS
         if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
         env:
           GTEST_OUTPUT: "xml:${{ env.GITHUB_WORKSPACE }}/junit_reports/regression/ns/"
           protocol: ns
-        run: |
-          # Run simulator and wait for it to to be ready
-          ./${{ env.regression_simulator_folder }}/regression_simulator &
-          while [ ! -f ready ]; do sleep 1; done
-          
-          # Set trap that will catch failed test (8) and successful test (0) and kill simulator gracefully, then exit with trapped code
-          trap "rc=$?; echo Killing simulator; pid=$(pgrep -f regression_simulator); rm ready; wait $pid; echo Simulator killed successfully; exit $rc" 0 8
-          
-          # Perform tests
-          ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
+        run: ./regression_test_run.sh
 
       - name: Protocol regression test - LT
         if: ${{ (success() || failure()) && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
         env:
           GTEST_OUTPUT: "xml:${{ env.GITHUB_WORKSPACE }}/junit_reports/regression/lt/"
           protocol: lt
-        run: |
-          # Run simulator and wait for it to to be ready
-          ./${{ env.regression_simulator_folder }}/regression_simulator &
-          while [ ! -f ready ]; do sleep 1; done
-          
-          # Set trap that will catch failed test (8) and successful test (0) and kill simulator gracefully, then exit with trapped code
-          trap "rc=$?; echo Killing simulator; pid=$(pgrep -f regression_simulator); rm ready; wait $pid; echo Simulator killed successfully; exit $rc" 0 8
-          
-          # Perform tests
-          ctest --output-on-failure -C ${{ matrix.cmake_build_type }} --tests-regex regression_test --test-dir build
+        run: ./regression_test_run.sh
 
       - name: Upload regression test results
         if: ${{ always() && matrix.name == 'Ubuntu 22.04 gcc-12 Release' }}
