<TBBAS-2595> Add caching of pdb, obj, lib, etc for MSVC

diff --git a/.github/workflows/package-artifacts.yml b/.github/workflows/package-artifacts.yml
--- a/.github/workflows/package-artifacts.yml
+++ b/.github/workflows/package-artifacts.yml
@@ -48,14 +48,17 @@ jobs:
 
           - os: windows-latest
             cache-key-os: windows
-            cmake-build-generator: 'Visual Studio 17 2022'
+            # cmake-build-generator: 'Visual Studio 17 2022'
+            cmake-build-generator: Ninja
             cmake-package-generator: NSIS
-            cmake-parallel: --parallel 2
+            cmake-parallel: ''
             # cmake-preset: --preset package
             cmake-preset: ''
             cmake-config: Release
             cmake-defines:
               -DOPENDAQ_ENABLE_TESTS=OFF
+              # -DCMAKE_CXX_FLAGS="/MP /bigobj"
+              # -DCMAKE_C_FLAGS="/MP /bigobj"
               # -DCMAKE_SYSTEM_NAME=Linux
               # -DCMAKE_SYSTEM_PROCESSOR=x86_64
               # -DOPENDAQ_BUILD_DOCUMENTATION=OFF
@@ -71,8 +74,10 @@ jobs:
               # -DOPENDAQ_ENABLE_WEBSOCKET_STREAMING=OFF
               # -DOPENDAQ_ENABLE_NATIVE_STREAMING=OFF
             cmake-compiler:
-              -DCMAKE_C_COMPILER_LAUNCHER=sccache
-              -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
+              -DCMAKE_C_COMPILER_LAUNCHER=ccache
+              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
+              # -DCMAKE_C_COMPILER=cl
+              # -DCMAKE_CXX_COMPILER=cl
 
           - os: macos-13
             cache-key-os: macos13
@@ -137,31 +142,15 @@ jobs:
       - name: Install dependencies Windows
         if: runner.os == 'Windows'
         run: |
-          choco install nsis sccache -y
-
-      - name: Prepare MSBuild for sccache
-        if: runner.os == 'Windows'
-        run: |
-          $wrapperDir = "$env:GITHUB_WORKSPACE\sccache-wrapper"
-          New-Item -ItemType Directory -Force -Path $wrapperDir
-
-          $msvcCl = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\*\bin\Hostx64\x64\cl.exe"
-
-          $batFile = Join-Path $wrapperDir "cl.bat"
-          Set-Content $batFile -Value "@echo off`nsccache `"$msvcCl`" %*"
-
-          Add-Content -Path $env:GITHUB_ENV -Value "PATH=$wrapperDir`;$env:PATH"
-
-          Write-Host "Wrapper dir added to PATH: $wrapperDir"
-          Write-Host $env:PATH
+          choco install ccache ninja nsis vswhere -y
 
       - name: Install dependencies MacOS
         if: runner.os == 'macOS'
         run: |
           brew install ccache
 
-      - name: Restore compiler cache (Unix)
-        if: matrix.os != 'windows-latest'
+      - name: Restore compiler cache
+        # if: matrix.os != 'windows-latest'
         uses: actions/cache@v4
         with:
           path: ${{ env.CCACHE_DIR }}
@@ -169,14 +158,57 @@ jobs:
           restore-keys: |
             ccache-${{ runner.os }}-
 
-      - name: Restore compiler cache (Windows)
-        if: matrix.os == 'windows-latest'
-        uses: actions/cache@v4
-        with:
-          path: ${{ env.SCCACHE_DIR }}
-          key: sccache-msvc-${{ hashFiles('**/*.c','**/*.cpp') }}
-          restore-keys: |
-            sccache-msvc-
+      - name: Setup MSVC environment
+        if: runner.os == 'Windows'
+        shell: powershell
+        run: |
+          $vsPath = vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
+          if (-not $vsPath) { Write-Error "Visual Studio not found"; exit 1 }
+
+          $vcvarsall = Join-Path $vsPath 'VC\Auxiliary\Build\vcvarsall.bat'
+          if (-not (Test-Path $vcvarsall)) { Write-Error "vcvarsall.bat not found"; exit 1 }
+
+          cmd /c "`"$vcvarsall`" x64 && set" | ForEach-Object {
+            if ($_ -match "^(.*?)=(.*)$") {
+              $name = $matches[1]
+              $value = $matches[2]
+              echo "$name=$value" >> $env:GITHUB_ENV
+            }
+          }
+
+      # - name: Setup MSBuild
+      #   if: matrix.os == 'windows-latest'
+      #   uses: microsoft/setup-msbuild@v2
+
+      # - name: Setup CC CXX paths (Windows)
+      #   if: matrix.os == 'windows-latest'
+      #   run: |
+      #     $cl = & vswhere -latest -products * -find **\Hostx64\x64\cl.exe
+      #     $cl = $cl | Select-Object -First 1
+      #     echo "CXX=$cl" >> $env:GITHUB_ENV
+      #     echo "CC=$cl" >> $env:GITHUB_ENV
+
+      # - name: Restore compiler cache (Windows)
+      #   if: matrix.os == 'windows-latest'
+      #   uses: actions/cache@v4
+      #   with:
+      #     path: ${{ env.SCCACHE_DIR }}
+      #     key: sccache-msvc-${{ hashFiles('**/*.c','**/*.cpp') }}
+      #     restore-keys: |
+      #       sccache-msvc-
+
+      # - name: Restore compiler cache (Windows)
+      #   uses: actions/cache@v4
+      #   if: matrix.os == 'windows-latest'
+      #   with:
+      #     path: |
+      #       build
+      #       ${{ github.workspace }}/**/*.obj
+      #       ${{ github.workspace }}/**/*.pdb
+      #       ${{ github.workspace }}/**/*.lib
+      #     key: msvc-build-${{ runner.os }}-${{ hashFiles('**/*.cpp', '**/*.h') }}
+      #     restore-keys: |
+      #       msvc-build-${{ runner.os }}-
 
       - name: Configure openDAQ CMake build
         run: cmake -S . -B build -G "${{ matrix.cmake-build-generator }}" ${{ matrix.cmake-preset }} ${{ matrix.cmake_defines }} ${{ matrix.cmake-compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.cmake-config }}
@@ -210,14 +242,14 @@ jobs:
           echo 'Artifact digest:. ${{ steps.opendaq-upload-artifact.outputs.artifact-digest }}'
 
       - name: Print compiler cache stats (Unix)
-        if: runner.os != 'Windows'
+        # if: runner.os != 'Windows'
         run: |
           echo "=== ccache stats ==="
           ccache -s
 
-      - name: Print compiler cache stats (Windows)
-        if: runner.os == 'Windows'
-        shell: powershell
-        run: |
-          echo "=== sccache stats ==="
-          sccache --show-stats
+      # - name: Print compiler cache stats (Windows)
+      #   if: runner.os == 'Windows'
+      #   shell: powershell
+      #   run: |
+      #     echo "=== sccache stats ==="
+      #     sccache --show-stats
